DROP TABLE IF EXISTS public.individual_offical_party_to_docket CASCADE;
DROP TABLE IF EXISTS public.fillings_on_behalf_of_org_relation CASCADE;
DROP TABLE IF EXISTS public.fillings_filed_by_individual CASCADE;
DROP TABLE IF EXISTS public.docket_petitioned_by_org CASCADE;
DROP TABLE IF EXISTS public.attachments CASCADE;
DROP TABLE IF EXISTS public.fillings CASCADE;
DROP TABLE IF EXISTS public.dockets CASCADE;
DROP TABLE IF EXISTS public.humans CASCADE;
DROP TABLE IF EXISTS public.organizations CASCADE;